### ISSUE TITLE
Bug: Name a page "storyblok"

### ISSUE THREAD

**Issue by anvanza** [Media-Lounge/magento2-storyblok-integration#17]
If you name your page "storyblok", the router is bypassed and the "story" value is not set.
Resulting in the error below:
`TypeError: Argument 2 passed to MediaLounge\Storyblok\Controller\Index\Index::setMetaFields() must be of the type array, null given`

I would add a check in Controller/Index/Index.php in the execute method. If the variable on L27 is null, throw a 404.

I named my very first page "storyblok" which resulted in an error before I even started.

**Comment by jahvi** [comment]
Thanks, I'll look into this one.

**Comment by jahvi** [comment]
Fixed in master e346350

This will be part of the next release.
